
"use client";
import store from "@/redux/store";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import "../style.css"

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "snappfood home",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body style={{margin:"0", padding:"0", width:"100%", backgroundColor:"#FF38AC"}}>{children}</body>
      </html>
    </Provider>
  );
}
